spring:
  liquibase:
    change-log: db.changelog/changelog.xml
  datasource:
    url: jdbc:postgresql://192.168.99.100:5432/user_service
    password: password
    username: postgres

  kafka:
    bootstrap-servers: 192.168.99.100:29092
